const ChannelList = [
  {
    name: "A&E",
    url: "https://xyzdddd.mizhls.ru/lb/premium302/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/a-and-e-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "A.and.E.US.-.Eastern.Feed.us",
  },
  {
    name: "ABC (WFAA)",
    url: "https://xyzdddd.mizhls.ru/lb/premium51/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/us-local/abc-8-wfaa-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "ABC.(WFAA).Dallas,.TX.us",
  },
  {
    name: "ABCNY",
    url: "https://xyzdddd.mizhls.ru/lb/premium766/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/us-local/abc-7-wabc-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "ABC.(WABC).New.York,.NY.us",
  },
  {
    name: "ACC Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium664/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/acc-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "ACC.Network.us",
  },
  {
    name: "Altitude Sports",
    url: "https://xyzdddd.mizhls.ru/lb/premium923/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/altitude-sports-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Altitude.Sports.-.Denver.us",
  },
  {
    name: "AMC",
    url: "https://xyzdddd.mizhls.ru/lb/premium303/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/amc-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "AMC.-.Eastern.Feed.us",
  },
  {
    name: "Animal Planet",
    url: "https://xyzdddd.mizhls.ru/lb/premium304/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/animal-planet-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Animal.Planet.US.-.East.us",
  },
  {
    name: "AXS TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium742/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/axs-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "AXS.TV.USA.HD.us",
  },
  {
    name: "BBC America (BBCA)",
    url: "https://xyzdddd.mizhls.ru/lb/premium305/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/bbc-america-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "BBC.America.-.East.us",
  },
  {
    name: "BBC Four",
    url: "https://xyzdddd.mizhls.ru/lb/premium359/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-four-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "BBC.Four.HD.uk",
  },
  {
    name: "BBC News Channel HD",
    url: "https://xyzdddd.mizhls.ru/lb/premium349/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-news-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "9206",
  },
  {
    name: "BBC One",
    url: "https://xyzdddd.mizhls.ru/lb/premium356/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-one-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "BBC.One.EastHD.uk",
  },
  {
    name: "BBC Three",
    url: "https://xyzdddd.mizhls.ru/lb/premium358/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-three-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "BBC.Three.HD.uk",
  },
  {
    name: "BBC Two",
    url: "https://xyzdddd.mizhls.ru/lb/premium357/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-two-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "BBC.Two.HD.uk",
  },
  {
    name: "BeIN SPORTS",
    url: "https://xyzdddd.mizhls.ru/lb/premium425/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/bein-sports-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "beINSports.us",
  },
  {
    name: "beIN SPORTS en Espanol",
    url: "https://xyzdddd.mizhls.ru/lb/premium372/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/bein-sports-espanol-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "beIN.Sports.HDTV.(Spanish).(beINHD).us",
  },
  {
    name: "BET",
    url: "https://xyzdddd.mizhls.ru/lb/premium306/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/bet-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "BET.-.Eastern.Feed.us",
  },
  {
    name: "BIG TEN Network (BTN)",
    url: "https://xyzdddd.mizhls.ru/lb/premium397/index.m3u8",
    logo: "https://btn.com/wp-content/uploads/2022/01/share-image.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Big.Ten.Network.us",
  },
  {
    name: "Boomerang",
    url: "https://xyzdddd.mizhls.ru/lb/premium648/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/boomerang-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Boomerang.us",
  },
  {
    name: "Bravo",
    url: "https://xyzdddd.mizhls.ru/lb/premium307/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/bravo-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Bravo.USA.-.Eastern.Feed.us",
  },
  {
    name: "C SPAN 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium750/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/c-span-1-us.png?raw=true",
    group: "USA (DADDY LIVE)",
    tvgId: "C-SPAN.us",
  },
  {
    name: "Cartoon Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium339/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cartoon-network-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Cartoon.Network.USA.-.Eastern.Feed.us",
  },
  {
    name: "CBC",
    url: "https://xyzdddd.mizhls.ru/lb/premium832/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/cbc-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "CBCToronto(English).ca",
  },
  {
    name: "CBS (WWJ)",
    url: "https://xyzdddd.mizhls.ru/lb/premium52/index.m3u8",
    logo: "https://i.imgur.com/qyUcJBI.png",
    group: "USA (DADDY LIVE)",
    tvgId: "CBS.(WWJ).Detroit,.MI.us",
  },
  {
    name: "CBS Sports Network (CBSSN)",
    url: "https://xyzdddd.mizhls.ru/lb/premium308/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cbs-sports-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "CBS.Sports.Network.USA.us",
  },
  {
    name: "CBSNY",
    url: "https://xyzdddd.mizhls.ru/lb/premium767/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/us-local/cbs-2-wcbs-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "CBS.(WCBS).New.York,.NY.us",
  },
  {
    name: "Channel 4",
    url: "https://xyzdddd.mizhls.ru/lb/premium354/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/channel-4-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Channel.4.HD.uk",
  },
  {
    name: "Channel 5",
    url: "https://xyzdddd.mizhls.ru/lb/premium355/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/channel-5-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Channel.5.uk",
  },
  {
    name: "Cinemax",
    url: "https://xyzdddd.mizhls.ru/lb/premium374/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cinemax-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Cinemax.-.Eastern.Feed.us",
  },
  {
    name: "Citytv",
    url: "https://xyzdddd.mizhls.ru/lb/premium831/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/city-tv-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "CITY.Montreal,.QC.ca",
  },
  {
    name: "Cleo TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium715/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/cleo-tv-us.png?raw=true",
    group: "USA (DADDY LIVE)",
    tvgId: "CLEO.TV.us",
  },
  {
    name: "CMT",
    url: "https://xyzdddd.mizhls.ru/lb/premium647/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cmt-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "CMT.US.-.Eastern.Feed.us",
  },
  {
    name: "CNBC",
    url: "https://xyzdddd.mizhls.ru/lb/premium309/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cnbc-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "CNBC.USA.us",
  },
  {
    name: "CNN",
    url: "https://xyzdddd.mizhls.ru/lb/premium345/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cnn-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "CNN.us",
  },
  {
    name: "Comedy Central",
    url: "https://xyzdddd.mizhls.ru/lb/premium310/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/comedy-central-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Comedy.Central.(US).-.Eastern.Feed.us",
  },
  {
    name: "Comet",
    url: "https://xyzdddd.mizhls.ru/lb/premium696/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/comet-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Comet.us",
  },
  {
    name: "Cooking Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium697/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cooking-channel-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "The.Cooking.Channel.us",
  },
  {
    name: "COZI TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium748/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cozi-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "COZITV.us",
  },
  {
    name: "Crime+ Investigation",
    url: "https://xyzdddd.mizhls.ru/lb/premium669/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/crime-and-investigation-uk.png?raw=true",
    group: "USA (DADDY LIVE)",
    tvgId: "Crime.and.Investigation.Network.USA.HD.us",
  },
  {
    name: "CTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium602/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/ctv-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "CTV.(CFCN).Calgary,.AB.ca",
  },
  {
    name: "CTV 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium838/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/ctv-2-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "CTV.Two.Ottawa/CHRO.(CTV2O).ca",
  },
  {
    name: "CW (WUCW)",
    url: "https://xyzdddd.mizhls.ru/lb/premium300/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/cw-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "CW.(WUCW).St..Paul,.MN.us",
  },
  {
    name: "Dave",
    url: "https://xyzdddd.mizhls.ru/lb/premium348/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/dave-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "U.and.Dave.HD.uk",
  },
  {
    name: "Destination America",
    url: "https://xyzdddd.mizhls.ru/lb/premium651/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/destination-america-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Destination.America.us",
  },
  {
    name: "Discovery Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium313/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/discovery-channel-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Discovery.Channel.(US).-.Eastern.Feed.us",
  },
  {
    name: "Discovery Family",
    url: "https://xyzdddd.mizhls.ru/lb/premium657/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/discovery-family-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Discovery.Family.Channel.us",
  },
  {
    name: "Discovery Life Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium311/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/discovery-life-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Discovery.Life.Channel.us",
  },
  {
    name: "Disney Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium312/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/disney-channel-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Disney.-.Eastern.Feed.us",
  },
  {
    name: "Disney JR",
    url: "https://xyzdddd.mizhls.ru/lb/premium652/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/disney-junior-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Disney.Junior.USA.-.East.us",
  },
  {
    name: "Disney XD",
    url: "https://xyzdddd.mizhls.ru/lb/premium314/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/disney-xd-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Disney.XD.USA.-.Eastern.Feed.us",
  },
  {
    name: "E! Entertainment Television",
    url: "https://xyzdddd.mizhls.ru/lb/premium315/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/e-entertainment-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "E!.Entertainment.USA.-.Eastern.Feed.us",
  },
  {
    name: "E4 Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium363/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/06/E4_Logo.png",
    group: "UK (DADDY LIVE)",
    tvgId: "E4.HD.uk",
  },
  {
    name: "ESPN",
    url: "https://xyzdddd.mizhls.ru/lb/premium44/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/espn-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "ESPN.us",
  },
  {
    name: "ESPN 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium45/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/espn-2-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "ESPN2.us",
  },
  {
    name: "ESPN Deportes",
    url: "https://xyzdddd.mizhls.ru/lb/premium375/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/espn-deportes-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "ESPN.Deportes.us",
  },
  {
    name: "ESPNews",
    url: "https://xyzdddd.mizhls.ru/lb/premium288/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/espnews-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "ESPN.News.us",
  },
  {
    name: "ESPNU",
    url: "https://xyzdddd.mizhls.ru/lb/premium316/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/ESPN_U_logo.svg/1200px-ESPN_U_logo.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "ESPNU.On.Demand.us",
  },
  {
    name: "EuroSport 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium41/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/eurosport-1-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Eurosport.1.HD.uk",
  },
  {
    name: "EuroSport 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium42/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/eurosport-2-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Eurosport.2.HD.uk",
  },
  {
    name: "FanDuel SN Detroit",
    url: "https://xyzdddd.mizhls.ru/lb/premium891/index.m3u8",
    logo: "https://i.imgur.com/1MDxLZf.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Detroit.HD.us",
  },
  {
    name: "FanDuel SN Florida",
    url: "https://xyzdddd.mizhls.ru/lb/premium892/index.m3u8",
    logo: "https://i.imgur.com/fuCM2ei.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Florida.us",
  },
  {
    name: "FanDuel SN Great Lakes",
    url: "https://xyzdddd.mizhls.ru/lb/premium893/index.m3u8",
    logo: "https://i.imgur.com/mPpaZCR.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Great.Lakes.us",
  },
  {
    name: "FanDuel SN Indiana",
    url: "https://xyzdddd.mizhls.ru/lb/premium894/index.m3u8",
    logo: "https://i.imgur.com/HUgEVWQ.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Indiana.us",
  },
  {
    name: "FanDuel SN Kansas City",
    url: "https://xyzdddd.mizhls.ru/lb/premium895/index.m3u8",
    logo: "https://i.imgur.com/Oo4Fayt.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Midwest.-.Kansas.City.us",
  },
  {
    name: "FanDuel SN Midwest",
    url: "https://xyzdddd.mizhls.ru/lb/premium896/index.m3u8",
    logo: "https://i.imgur.com/gdm5VCX.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Midwest.St..Louis.us",
  },
  {
    name: "FanDuel SN North",
    url: "https://xyzdddd.mizhls.ru/lb/premium898/index.m3u8",
    logo: "https://i.imgur.com/qfu8djF.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.North.us",
  },
  {
    name: "FanDuel SN Ohio",
    url: "https://xyzdddd.mizhls.ru/lb/premium899/index.m3u8",
    logo: "https://i.imgur.com/U4kf3x6.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Ohio.-.Cleveland.us",
  },
  {
    name: "FanDuel SN Oklahoma",
    url: "https://xyzdddd.mizhls.ru/lb/premium900/index.m3u8",
    logo: "https://i.imgur.com/mx7lyh5.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Oklahoma.us",
  },
  {
    name: "FanDuel SN SoCal",
    url: "https://xyzdddd.mizhls.ru/lb/premium902/index.m3u8",
    logo: "https://i.imgur.com/yywNI3M.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.SoCal.us",
  },
  {
    name: "FanDuel SN South",
    url: "https://xyzdddd.mizhls.ru/lb/premium903/index.m3u8",
    logo: "https://i.imgur.com/SZfJfVM.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.South.us",
  },
  {
    name: "FanDuel SN Southeast",
    url: "https://xyzdddd.mizhls.ru/lb/premium904/index.m3u8",
    logo: "https://i.imgur.com/Y7pFt5h.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Southeast.us",
  },
  {
    name: "FanDuel SN Sun",
    url: "https://xyzdddd.mizhls.ru/lb/premium905/index.m3u8",
    logo: "https://i.imgur.com/IapPEUD.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Fanduel.Sports.Sun.us",
  },
  {
    name: "FanDuel SN West",
    url: "https://xyzdddd.mizhls.ru/lb/premium906/index.m3u8",
    logo: "https://i.imgur.com/cv546ko.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.West.us",
  },
  {
    name: "FanDuel SN Wisconsin",
    url: "https://xyzdddd.mizhls.ru/lb/premium907/index.m3u8",
    logo: "https://i.imgur.com/Ku0ibaF.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FanDuel.Sports.Network.Wisconsin.us",
  },
  {
    name: "Film4",
    url: "https://xyzdddd.mizhls.ru/lb/premium688/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/film-4-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Film4.HD.uk",
  },
  {
    name: "FOX (WSVN)",
    url: "https://xyzdddd.mizhls.ru/lb/premium54/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "FOX.(WSVN).Miami,.FL.us",
  },
  {
    name: "Fox Business",
    url: "https://xyzdddd.mizhls.ru/lb/premium297/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-business-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Fox.Business.us",
  },
  {
    name: "Fox Cricket",
    url: "https://xyzdddd.mizhls.ru/lb/premium369/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/8c9d06e33d31b0ac3804acb5d5f2d1050f0c1384/countries/australia/fox-sports-cricket-501-au.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FoxCricket.alt.au",
  },
  {
    name: "FOX Deportes",
    url: "https://xyzdddd.mizhls.ru/lb/premium643/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/FOX_Deportes_logo.svg/800px-FOX_Deportes_logo.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "8486",
  },
  {
    name: "Fox News",
    url: "https://xyzdddd.mizhls.ru/lb/premium347/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-news-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Fox.News.us",
  },
  {
    name: "FOX Soccer Plus",
    url: "https://xyzdddd.mizhls.ru/lb/premium756/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-soccer-plus-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FOX.Soccer.Plus.HD.us",
  },
  {
    name: "Fox Sports 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium39/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-sports-1-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Fox.Sports.1.us",
  },
  {
    name: "Fox Sports 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium758/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-sports-2-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Fox.Sports.2.us",
  },
  {
    name: "FOX Sports 502",
    url: "https://xyzdddd.mizhls.ru/lb/premium820/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8c9d06e33d31b0ac3804acb5d5f2d1050f0c1384/countries/australia/fox-sports-league-502-au.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FoxLeague.au",
  },
  {
    name: "FOX Sports 503",
    url: "https://xyzdddd.mizhls.ru/lb/premium821/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8c9d06e33d31b0ac3804acb5d5f2d1050f0c1384/countries/australia/fox-sports-503-au.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FoxSports503.au",
  },
  {
    name: "FOX Sports 504",
    url: "https://xyzdddd.mizhls.ru/lb/premium822/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8c9d06e33d31b0ac3804acb5d5f2d1050f0c1384/countries/australia/fox-sports-footy-504-au.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FoxFooty.au",
  },
  {
    name: "FOX Sports 505",
    url: "https://xyzdddd.mizhls.ru/lb/premium823/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/fox-sports-505-au.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FoxSports505.au",
  },
  {
    name: "FOX Sports 506",
    url: "https://xyzdddd.mizhls.ru/lb/premium824/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/fox-sports-506-au.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "FoxSports506.au",
  },
  {
    name: "FOX Sports 507",
    url: "https://xyzdddd.mizhls.ru/lb/premium825/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8c9d06e33d31b0ac3804acb5d5f2d1050f0c1384/countries/australia/fox-sports-507-au.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySpMainEv.uk",
  },
  {
    name: "Fox Weather Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium775/index.m3u8",
    logo: "https://provider-static.plex.tv/epg/cms/production/5822536e-f8a5-44ea-a82f-a73be1b983e8/fox_weather_horizontal.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Fox.Weather.(WDCA4).Washington,.DC.us",
  },
  {
    name: "FOXNY",
    url: "https://xyzdddd.mizhls.ru/lb/premium768/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fox-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "FOX.(WNYW).New.York,.NY.us",
  },
  {
    name: "Freeform",
    url: "https://xyzdddd.mizhls.ru/lb/premium301/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/freeform-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Freeform.-.East.Feed.us",
  },
  {
    name: "FX",
    url: "https://xyzdddd.mizhls.ru/lb/premium317/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fx-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "FX.Networks.East.Coast.us",
  },
  {
    name: "FX Movie Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium381/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fxm-movie-channel-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "FX.Movie.Channel.us",
  },
  {
    name: "FXX",
    url: "https://xyzdddd.mizhls.ru/lb/premium298/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fxx-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "FXX.USA.-.Eastern.us",
  },
  {
    name: "FYI",
    url: "https://xyzdddd.mizhls.ru/lb/premium665/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/fyi-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "FYI.USA.-.Eastern.us",
  },
  {
    name: "Game Show Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium319/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/game-show-network-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Game.Show.Network.-.East.us",
  },
  {
    name: "Global",
    url: "https://xyzdddd.mizhls.ru/lb/premium836/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/global-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "GlobalToronto(English).ca",
  },
  {
    name: "Gold",
    url: "https://xyzdddd.mizhls.ru/lb/premium687/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/gold-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Gold.uk",
  },
  {
    name: "GOLF Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium318/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nbc-golf-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Golf.Channel.USA.us",
  },
  {
    name: "Great American Family",
    url: "https://xyzdddd.mizhls.ru/lb/premium699/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/great-american-family-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Great.American.Family.us",
  },
  {
    name: "Grit Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium752/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/grit-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Grit.TV.us",
  },
  {
    name: "Hallmark Movies & Mysterie",
    url: "https://xyzdddd.mizhls.ru/lb/premium296/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hallmark-mystery-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Hallmark.Mystery.Eastern.-.HD.us",
  },
  {
    name: "HBO",
    url: "https://xyzdddd.mizhls.ru/lb/premium321/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hbo-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HBO.-.Eastern.Feed.us",
  },
  {
    name: "HBO Comedy",
    url: "https://xyzdddd.mizhls.ru/lb/premium690/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hbo-comedy-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HBO.Comedy.HD.-.East.us",
  },
  {
    name: "HBO Family",
    url: "https://xyzdddd.mizhls.ru/lb/premium691/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hbo-family-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HBO.Family.-.Eastern.Feed.us",
  },
  {
    name: "HBO Signature",
    url: "https://xyzdddd.mizhls.ru/lb/premium693/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hbo-signature-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HBO.Signature.(HBO.3).-.Eastern.us",
  },
  {
    name: "HBO Zone",
    url: "https://xyzdddd.mizhls.ru/lb/premium694/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hbo-zone-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HBO.Zone.HD.-.East.us",
  },
  {
    name: "HBO2",
    url: "https://xyzdddd.mizhls.ru/lb/premium689/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hbo-2-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HBO.2.-.Eastern.Feed.us",
  },
  {
    name: "Headline News",
    url: "https://xyzdddd.mizhls.ru/lb/premium323/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hln-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HLN.us",
  },
  {
    name: "HGTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium382/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hgtv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "HGTV.USA.-.Eastern.Feed.us",
  },
  {
    name: "History",
    url: "https://xyzdddd.mizhls.ru/lb/premium322/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/History_Logo.svg/1000px-History_Logo.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "History.Channel.US.-.Eastern.Feed.us",
  },
  {
    name: "IFC TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium656/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/ifc-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Independent.Film.Channel.US.us",
  },
  {
    name: "Investigation Discovery (ID)",
    url: "https://xyzdddd.mizhls.ru/lb/premium324/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/investigation-discovery-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Investigation.Discovery.USA.-.Eastern.us",
  },
  {
    name: "ION",
    url: "https://xyzdddd.mizhls.ru/lb/premium325/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/ion-television-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "ION..-.Eastern.Feed.us",
  },
  {
    name: "ITV 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium350/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/itv-1-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "ITV1.HD.uk",
  },
  {
    name: "ITV 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium351/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/itv-2-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "ITV2.HD.uk",
  },
  {
    name: "ITV 3",
    url: "https://xyzdddd.mizhls.ru/lb/premium352/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/itv-3-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "ITV3.HD.uk",
  },
  {
    name: "ITV 4",
    url: "https://xyzdddd.mizhls.ru/lb/premium353/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/itv-4-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "ITV4.HD.uk",
  },
  {
    name: "Lifetime Movies Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium389/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/LMN_logo_2016.svg/1200px-LMN_logo_2016.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Lifetime.Movies.-.East.us",
  },
  {
    name: "Lifetime Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium326/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Logo_Lifetime_2020.svg/2560px-Logo_Lifetime_2020.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Lifetime.Network.US.-.Eastern.Feed.us",
  },
  {
    name: "Liverpool TV (LFC TV)",
    url: "https://xyzdddd.mizhls.ru/lb/premium826/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/lfctv-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "LFCTV.HD.uk",
  },
  {
    name: "Magnolia Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium299/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/magnolia-network-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Magnolia.-.East.us",
  },
  {
    name: "Marquee Sports Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium770/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/marquee-sports-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "MARQ.Marquee.Sports.Network.us",
  },
  {
    name: "MASN",
    url: "https://xyzdddd.mizhls.ru/lb/premium829/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/masn-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "MASN.us",
  },
  {
    name: "MAVTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium646/index.m3u8",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTowwKlIECbPIzGyK6WcOyg7FRXPP_7ips1MhqsUEk6&s",
    group: "USA (DADDY LIVE)",
    tvgId: "MavTV.USA.us",
  },
  {
    name: "METV",
    url: "https://xyzdddd.mizhls.ru/lb/premium662/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/me-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Me.TV.us",
  },
  {
    name: "MLB Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium399/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/mlb-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "MLB.Network.us",
  },
  {
    name: "Motor Trend",
    url: "https://xyzdddd.mizhls.ru/lb/premium661/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/motor-trend-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Motor.Trend.HD.us",
  },
  {
    name: "MSG",
    url: "https://xyzdddd.mizhls.ru/lb/premium765/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/msg-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "MSG.(Madison.Square.Gardens).us",
  },
  {
    name: "MSNBC",
    url: "https://xyzdddd.mizhls.ru/lb/premium327/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/msnbc-alt-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "MSNBC.USA.us",
  },
  {
    name: "MTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium371/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/mtv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "MTV.USA.-.Eastern.Feed.us",
  },
  {
    name: "MTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium367/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/mtv-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "MTV.MUSIC.uk",
  },
  {
    name: "MUTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium377/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/mutv-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "MUTV.HD.uk",
  },
  {
    name: "MY9TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium654/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/WWOR_NewJersey.svg/640px-WWOR_NewJersey.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "MNT.(WWOR).New.York,.NY.us",
  },
  {
    name: "Nat Geo Wild",
    url: "https://xyzdddd.mizhls.ru/lb/premium745/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nat-geo-wild-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "National.Geographic.Wild.us",
  },
  {
    name: "National Geographic (NGC)",
    url: "https://xyzdddd.mizhls.ru/lb/premium328/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/national-geographic-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "National.Geographic.US.-.Eastern.us",
  },
  {
    name: "NBA TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium404/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nba-tv-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NBA.TV.USA.us",
  },
  {
    name: "NBC (KNBC)",
    url: "https://xyzdddd.mizhls.ru/lb/premium53/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/us-local/nbc-4-knbc-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "NBC.(KNBC).Los.Angeles,.CA.us",
  },
  {
    name: "NBC Sports Bay Area",
    url: "https://xyzdddd.mizhls.ru/lb/premium753/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/nbc-sports-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NBC.Sports.Bay.Area.us",
  },
  {
    name: "NBC Sports Boston",
    url: "https://xyzdddd.mizhls.ru/lb/premium754/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/nbc-sports-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NBC.Sports.Boston.us",
  },
  {
    name: "NBC Sports California",
    url: "https://xyzdddd.mizhls.ru/lb/premium755/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/nbcsn-california-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NBC.Sports.California.us",
  },
  {
    name: "NBC Sports Chicago",
    url: "https://xyzdddd.mizhls.ru/lb/premium776/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nbc-sports-chicago-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NBCSportsChicago.us",
  },
  {
    name: "NBC Sports Philadelphia",
    url: "https://xyzdddd.mizhls.ru/lb/premium777/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/nbcsn-philadelphia-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NBC.Sports.Philadelphia.HDTV.(NBCSPAHD).us",
  },
  {
    name: "NBC Sports Washington",
    url: "https://xyzdddd.mizhls.ru/lb/premium778/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/nbcsn-washington-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Monumental.Sports.Network.us",
  },
  {
    name: "NBCNY",
    url: "https://xyzdddd.mizhls.ru/lb/premium769/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/NBC_logo.svg/2077px-NBC_logo.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "NBC.(WNBC).New.York,.NY.us",
  },
  {
    name: "NESN",
    url: "https://xyzdddd.mizhls.ru/lb/premium762/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nesn-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "New.England.Sports.Network.HDTV.(NESNHD).us",
  },
  {
    name: "Newsmax",
    url: "https://xyzdddd.mizhls.ru/lb/premium613/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/newsmax-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "NewsMax.TV.us",
  },
  {
    name: "NewsNation",
    url: "https://xyzdddd.mizhls.ru/lb/premium292/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/news-nation-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "NewsNation.-.Eastern.Feed.us",
  },
  {
    name: "NFL Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium405/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nfl-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NFL.Network.us",
  },
  {
    name: "NFL RedZone",
    url: "https://xyzdddd.mizhls.ru/lb/premium667/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/nfl-red-zone-hz-us.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NFL.RedZone.us",
  },
  {
    name: "NHL Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium663/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nhl-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "NHL.Network.USA.us",
  },
  {
    name: "NICK",
    url: "https://xyzdddd.mizhls.ru/lb/premium330/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nick-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Nickelodeon.USA.-.East.Feed.us",
  },
  {
    name: "NICK JR",
    url: "https://xyzdddd.mizhls.ru/lb/premium329/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/nick-jr-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Nick.Jr..-.East.us",
  },
  {
    name: "Nicktoons",
    url: "https://xyzdddd.mizhls.ru/lb/premium649/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Nicktoons.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Nicktoons.-.East.us",
  },
  {
    name: "Noovo",
    url: "https://xyzdddd.mizhls.ru/lb/premium835/index.m3u8",
    logo: "https://i.imgur.com/DK8UT1f.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "Noovo(CFJP)MontrealQC(src01).ca",
  },
  {
    name: "Oprah Winfrey Network (OWN)",
    url: "https://xyzdddd.mizhls.ru/lb/premium331/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/oprah-winfrey-network-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Oprah.Winfrey.Network.USA.Eastern.us",
  },
  {
    name: "Oxygen True Crime",
    url: "https://xyzdddd.mizhls.ru/lb/premium332/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/oxygen-true-crime-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Oxygen.-.Eastern.Feed.us",
  },
  {
    name: "Paramount Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium334/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/paramount-network-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Paramount.Network.USA.-.Eastern.Feed.us",
  },
  {
    name: "POP TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium653/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/pop-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "POP.-.East.us",
  },
  {
    name: "Racing Tv",
    url: "https://xyzdddd.mizhls.ru/lb/premium555/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/racing-tv-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Racing.TV.HD.uk",
  },
  {
    name: "RDS",
    url: "https://xyzdddd.mizhls.ru/lb/premium839/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/rds-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "RDS.(Réseau.des.sports).ca",
  },
  {
    name: "RDS 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium840/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/rds-2-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "CTV.--.Réseau.des.Sports.2.HDTV.(RDS2HD).ca",
  },
  {
    name: "RDS Info",
    url: "https://xyzdddd.mizhls.ru/lb/premium841/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/rds-info-ca.png",
    group: "Canada (DADDY LIVE)",
    tvgId: "RDS.Info.ca",
  },
  {
    name: "Reelz Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium293/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/reelz-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "ReelzChannel.us",
  },
  {
    name: "RTE 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium364/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/rte-one-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "RTE.One.HD.ie",
  },
  {
    name: "RTE 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium365/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/rte-2-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "RTE.Two.HD.ie",
  },
  {
    name: "S4C",
    url: "https://xyzdddd.mizhls.ru/lb/premium670/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/s4c-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "S4C.uk",
  },
  {
    name: "Science Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium294/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/discovery-science-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Science.us",
  },
  {
    name: "SEC Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium385/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/sec-network-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "SEC.Network.us",
  },
  {
    name: "Showtime",
    url: "https://xyzdddd.mizhls.ru/lb/premium333/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/showtime-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "ParamountpluswithShowtime.us",
  },
  {
    name: "SHOxBET",
    url: "https://xyzdddd.mizhls.ru/lb/premium685/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/sho-bet-us.png?raw=true",
    group: "USA (DADDY LIVE)",
    tvgId: "SHOXBET.-.Eastern.us",
  },
  {
    name: "Sky Arts",
    url: "https://xyzdddd.mizhls.ru/lb/premium683/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-arts-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Arts.HD.uk",
  },
  {
    name: "Sky Atlantic",
    url: "https://xyzdddd.mizhls.ru/lb/premium362/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Sky_Atlantic_-_Logo_2020.svg/2560px-Sky_Atlantic_-_Logo_2020.svg.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Atlantic.HD.uk",
  },
  {
    name: "Sky Cinema Action",
    url: "https://xyzdddd.mizhls.ru/lb/premium677/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-action-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Action.uk",
  },
  {
    name: "Sky Cinema Animation",
    url: "https://xyzdddd.mizhls.ru/lb/premium675/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-animation-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "SkyAnimationHD.uk",
  },
  {
    name: "Sky Cinema Drama",
    url: "https://xyzdddd.mizhls.ru/lb/premium680/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/sky-cinema-drama-uk.png?raw=true",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Drama.HD.uk",
  },
  {
    name: "Sky Cinema Family",
    url: "https://xyzdddd.mizhls.ru/lb/premium676/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-family-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Family.HD.uk",
  },
  {
    name: "Sky Cinema Greats",
    url: "https://xyzdddd.mizhls.ru/lb/premium674/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-greats-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Greats.uk",
  },
  {
    name: "Sky Cinema Hits",
    url: "https://xyzdddd.mizhls.ru/lb/premium673/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-hits-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Cinema.Hits.HD.uk",
  },
  {
    name: "Sky Cinema Premiere",
    url: "https://xyzdddd.mizhls.ru/lb/premium671/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-premiere-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Premiere.uk",
  },
  {
    name: "Sky Cinema Sci-Fi Horror",
    url: "https://xyzdddd.mizhls.ru/lb/premium681/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-sci-fi-and-horror-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Sci-Fi.HD.uk",
  },
  {
    name: "Sky Cinema Select",
    url: "https://xyzdddd.mizhls.ru/lb/premium672/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-select-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Cinema.Select.uk",
  },
  {
    name: "Sky Cinema Thriller",
    url: "https://xyzdddd.mizhls.ru/lb/premium679/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-cinema-thriller-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Thriller.HD.uk",
  },
  {
    name: "Sky Comedy",
    url: "https://xyzdddd.mizhls.ru/lb/premium684/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-comedy-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Comedy.HD.uk",
  },
  {
    name: "Sky Crime",
    url: "https://xyzdddd.mizhls.ru/lb/premium685/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-crime-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Crime.HD.uk",
  },
  {
    name: "Sky History",
    url: "https://xyzdddd.mizhls.ru/lb/premium686/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-history-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.HistoryHD.uk",
  },
  {
    name: "Sky Showcase",
    url: "https://xyzdddd.mizhls.ru/lb/premium682/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-showcase-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "SkyShowcaseHD.uk",
  },
  {
    name: "Sky Sport Top Event DE",
    url: "https://xyzdddd.mizhls.ru/lb/premium556/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/germany/sky-sport/sky-sport-top-event-de.png",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "Sky.Sport.Top.Event.de",
  },
  {
    name: "Sky Sports Action",
    url: "https://xyzdddd.mizhls.ru/lb/premium37/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-action-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.ActionHD.uk",
  },
  {
    name: "Sky Sports Arena",
    url: "https://xyzdddd.mizhls.ru/lb/premium36/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-arena-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "12358",
  },
  {
    name: "Sky Sports Cricket",
    url: "https://xyzdddd.mizhls.ru/lb/premium65/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/sky-sports-cricket-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.Cricket.uk",
  },
  {
    name: "Sky Sports F1",
    url: "https://xyzdddd.mizhls.ru/lb/premium60/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-f1-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.F1.HD.uk",
  },
  {
    name: "Sky Sports Football",
    url: "https://xyzdddd.mizhls.ru/lb/premium35/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-football-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sky.Sports.Football.HD.uk",
  },
  {
    name: "Sky Sports Golf",
    url: "https://xyzdddd.mizhls.ru/lb/premium70/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-golf-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.Golf.HD.uk",
  },
  {
    name: "Sky Sports Main Event",
    url: "https://xyzdddd.mizhls.ru/lb/premium38/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/hd/sky-sports-main-event-hd-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySpMainEvHD.uk",
  },
  {
    name: "Sky Sports MIX",
    url: "https://xyzdddd.mizhls.ru/lb/premium557/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-mix-uk.png",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "Sky.Mix.HD.uk",
  },
  {
    name: "Sky Sports News",
    url: "https://xyzdddd.mizhls.ru/lb/premium366/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-sports-news-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.News.HD.uk",
  },
  {
    name: "Sky sports Premier League",
    url: "https://xyzdddd.mizhls.ru/lb/premium130/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/sky-sports-premier-league-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.PL.uk",
  },
  {
    name: "Sky Sports Racing",
    url: "https://xyzdddd.mizhls.ru/lb/premium554/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/sky-sports-racing-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SkySp.Racing.HD.uk",
  },
  {
    name: "Sky Witness HD",
    url: "https://xyzdddd.mizhls.ru/lb/premium361/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-witness-uk.png",
    group: "UK (DADDY LIVE)",
    tvgId: "Sky.Witness.HD.uk",
  },
  {
    name: "Spectrum Sportsnet LA",
    url: "https://xyzdddd.mizhls.ru/lb/premium764/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/spectrum-sportsnet-la-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Spectrum.Sportsnet.Lakers.us",
  },
  {
    name: "Sportsnet 360",
    url: "https://xyzdddd.mizhls.ru/lb/premium409/index.m3u8",
    logo: "https://w7.pngwing.com/pngs/746/852/png-transparent-sportsnet-360-cfac-calgary-flames-national-hockey-league-others-text-logo-world.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sportsnet.360.ca",
  },
  {
    name: "Sportsnet East",
    url: "https://xyzdddd.mizhls.ru/lb/premium408/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/sportsnet-east-ca.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sportsnet.(East).-.Satellite/Digital.ca",
  },
  {
    name: "SportsNet New York (SNY)",
    url: "https://xyzdddd.mizhls.ru/lb/premium759/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/SNY_logo.svg/1200px-SNY_logo.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SportsNetNewYork.us",
  },
  {
    name: "Sportsnet One",
    url: "https://xyzdddd.mizhls.ru/lb/premium411/index.m3u8",
    logo: "https://cdn.tvpassport.com/image/station/240x135/v2/s68859_h15_ac.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sportsnet.One.ca",
  },
  {
    name: "Sportsnet Ontario",
    url: "https://xyzdddd.mizhls.ru/lb/premium406/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/sportsnet-ontario-ca.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sportsnet.(Ontario).ca",
  },
  {
    name: "SportsNet Pittsburgh",
    url: "https://xyzdddd.mizhls.ru/lb/premium922/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/sportsnet-pittsburgh-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "SportsNet.Pittsburgh.us",
  },
  {
    name: "Sportsnet West",
    url: "https://xyzdddd.mizhls.ru/lb/premium407/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/sportsnet-west-ca.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sportsnet.(West).-.Satellite/Digital.ca",
  },
  {
    name: "Sportsnet World",
    url: "https://xyzdddd.mizhls.ru/lb/premium410/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/sportsnet-world-ca.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Sportsnet.World.ca",
  },
  {
    name: "Starz",
    url: "https://xyzdddd.mizhls.ru/lb/premium335/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/starz-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Starz.-.Eastern.us",
  },
  {
    name: "Sundance TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium658/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/sundance-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "SundanceTV.USA.-.East.us",
  },
  {
    name: "SuperSport Action",
    url: "https://xyzdddd.mizhls.ru/lb/premium420/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-action-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "ACTION.za",
  },
  {
    name: "SuperSport Cricket",
    url: "https://xyzdddd.mizhls.ru/lb/premium368/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-cricket-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "CRICKET.za",
  },
  {
    name: "Supersport Football",
    url: "https://xyzdddd.mizhls.ru/lb/premium56/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-football-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "FOOTBALL.za",
  },
  {
    name: "SuperSport Golf",
    url: "https://xyzdddd.mizhls.ru/lb/premium422/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-golf-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "GOLF.za",
  },
  {
    name: "SuperSport Grandstand",
    url: "https://xyzdddd.mizhls.ru/lb/premium412/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-grandstand-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "GRANDSTAND.za",
  },
  {
    name: "SuperSport LaLiga",
    url: "https://xyzdddd.mizhls.ru/lb/premium415/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-laliga-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "LA.LIGA.za",
  },
  {
    name: "SuperSport MaXimo 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium572/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-maximo1-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "MAXIMO.1.za",
  },
  {
    name: "SuperSport Motorsport",
    url: "https://xyzdddd.mizhls.ru/lb/premium424/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-motorsport-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "MOTORSPORT.za",
  },
  {
    name: "SuperSport Premier league",
    url: "https://xyzdddd.mizhls.ru/lb/premium414/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-premier-league-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "SS.Premier.League.za",
  },
  {
    name: "SuperSport PSL",
    url: "https://xyzdddd.mizhls.ru/lb/premium413/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-psl-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "PSL.za",
  },
  {
    name: "SuperSport Rugby",
    url: "https://xyzdddd.mizhls.ru/lb/premium421/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-rugby-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "RUGBY.za",
  },
  {
    name: "SuperSport Tennis",
    url: "https://xyzdddd.mizhls.ru/lb/premium423/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-tennis-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "TENNIS.za",
  },
  {
    name: "SuperSport Variety 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium416/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-variety1-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "VARIETY.1.za",
  },
  {
    name: "SuperSport Variety 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium417/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-variety2-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "VARIETY.2.za",
  },
  {
    name: "SuperSport Variety 3",
    url: "https://xyzdddd.mizhls.ru/lb/premium418/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-variety3-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "VARIETY.3.za",
  },
  {
    name: "SuperSport Variety 4",
    url: "https://xyzdddd.mizhls.ru/lb/premium419/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/8d25ddd79ca2f9cd033b808c45cccd2b3da563ee/countries/south-africa/supersport-variety4-za.png?raw=true",
    group: "SPORTS MISC (DADDY LIVE)",
    tvgId: "VARIETY.4.za",
  },
  {
    name: "SYFY",
    url: "https://xyzdddd.mizhls.ru/lb/premium373/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/syfy-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Syfy.-.Eastern.Feed.us",
  },
  {
    name: "TBS",
    url: "https://xyzdddd.mizhls.ru/lb/premium336/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/tbs-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "TBS.-.East.us",
  },
  {
    name: "TCM",
    url: "https://xyzdddd.mizhls.ru/lb/premium644/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/tcm-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Turner.Classic.Movies.USA.us",
  },
  {
    name: "TeenNick",
    url: "https://xyzdddd.mizhls.ru/lb/premium650/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/teen-nick-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "TeenNick.-.Eastern.us",
  },
  {
    name: "Telemundo",
    url: "https://xyzdddd.mizhls.ru/lb/premium131/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/telemundo-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Telemundo..-.Eastern.Feed.us",
  },
  {
    name: "Tennis Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium40/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/tennis-channel-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Cup.tennis",
  },
  {
    name: "Tennis+ 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium700/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.1.tennis",
  },
  {
    name: "Tennis+ 10",
    url: "https://xyzdddd.mizhls.ru/lb/premium709/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "(no tvg-id)",
  },
  {
    name: "Tennis+ 11",
    url: "https://xyzdddd.mizhls.ru/lb/premium710/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "(no tvg-id)",
  },
  {
    name: "Tennis+ 12",
    url: "https://xyzdddd.mizhls.ru/lb/premium711/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "(no tvg-id)",
  },
  {
    name: "Tennis+ 13",
    url: "https://xyzdddd.mizhls.ru/lb/premium712/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "(no tvg-id)",
  },
  {
    name: "Tennis+ 14",
    url: "https://xyzdddd.mizhls.ru/lb/premium713/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "(no tvg-id)",
  },
  {
    name: "Tennis+ 15",
    url: "https://xyzdddd.mizhls.ru/lb/premium714/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "(no tvg-id)",
  },
  {
    name: "Tennis+ 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium701/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.2.tennis",
  },
  {
    name: "Tennis+ 3",
    url: "https://xyzdddd.mizhls.ru/lb/premium702/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.3.tennis",
  },
  {
    name: "Tennis+ 4",
    url: "https://xyzdddd.mizhls.ru/lb/premium703/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.4.tennis",
  },
  {
    name: "Tennis+ 5",
    url: "https://xyzdddd.mizhls.ru/lb/premium704/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.5.tennis",
  },
  {
    name: "Tennis+ 6",
    url: "https://xyzdddd.mizhls.ru/lb/premium705/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.6.tennis",
  },
  {
    name: "Tennis+ 7",
    url: "https://xyzdddd.mizhls.ru/lb/premium706/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.7.tennis",
  },
  {
    name: "Tennis+ 8",
    url: "https://xyzdddd.mizhls.ru/lb/premium707/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.8.tennis",
  },
  {
    name: "Tennis+ 9",
    url: "https://xyzdddd.mizhls.ru/lb/premium708/index.m3u8",
    logo: "https://sbgi.net/wp-content/uploads/2022/09/tennis_channel_color_horz_wht-1.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Tennis.Plus.9.tennis",
  },
  {
    name: "The Food Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium384/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Food_Network_logo.svg/1200px-Food_Network_logo.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Food.Network.USA.-.Eastern.Feed.us",
  },
  {
    name: "The Hallmark Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium320/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/hallmark-channel-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Hallmark.-.Eastern.Feed.us",
  },
  {
    name: "The Weather Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium394/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/The_Weather_Channel_logo_2005-present.svg/1200px-The_Weather_Channel_logo_2005-present.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "The.Weather.Channel.us",
  },
  {
    name: "TLC",
    url: "https://xyzdddd.mizhls.ru/lb/premium337/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/tlc-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "TLC.USA.-.Eastern.us",
  },
  {
    name: "TMC Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium698/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TMC_logo.svg/1200px-TMC_logo.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "TMC.(US).-.Eastern.Feed.us",
  },
  {
    name: "TNT",
    url: "https://xyzdddd.mizhls.ru/lb/premium338/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/tnt-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "TNT.-.Eastern.Feed.us",
  },
  {
    name: "TNT Sports 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium31/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/tnt-sports-1-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TNT.Sports.1.HD.uk",
  },
  {
    name: "TNT Sports 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium32/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/tnt-sports-2-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TNT.Sports.2.HD.uk",
  },
  {
    name: "TNT Sports 3",
    url: "https://xyzdddd.mizhls.ru/lb/premium33/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/tnt-sports-3-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TNT.Sports.3.HD.uk",
  },
  {
    name: "TNT Sports 4",
    url: "https://xyzdddd.mizhls.ru/lb/premium34/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/tnt-sports-4-uk.png?raw=true",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TNT.Sports.4.HD.uk",
  },
  {
    name: "Travel Channel",
    url: "https://xyzdddd.mizhls.ru/lb/premium340/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/travel-channel-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Travel.US.-.East.us",
  },
  {
    name: "TruTV",
    url: "https://xyzdddd.mizhls.ru/lb/premium341/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/tru-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "truTV.USA.-.Eastern.us",
  },
  {
    name: "TSN1",
    url: "https://xyzdddd.mizhls.ru/lb/premium111/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/TSN1.svg/2560px-TSN1.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TSN1.ca",
  },
  {
    name: "TSN2",
    url: "https://xyzdddd.mizhls.ru/lb/premium112/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/TSN2_New_Logo.svg/2560px-TSN2_New_Logo.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TSN2.ca",
  },
  {
    name: "TSN3",
    url: "https://xyzdddd.mizhls.ru/lb/premium113/index.m3u8",
    logo: "https://cdn.tvpassport.com/image/station/240x135/v2/s90119_h15_aa.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TSN3.ca",
  },
  {
    name: "TSN4",
    url: "https://xyzdddd.mizhls.ru/lb/premium114/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/TSN4.svg/1280px-TSN4.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TSN4.ca",
  },
  {
    name: "TSN5",
    url: "https://xyzdddd.mizhls.ru/lb/premium115/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/TSN5.svg/1200px-TSN5.svg.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TSN5.ca",
  },
  {
    name: "TUDN",
    url: "https://xyzdddd.mizhls.ru/lb/premium66/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/tudn-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "TUDN.us",
  },
  {
    name: "TV ONE",
    url: "https://xyzdddd.mizhls.ru/lb/premium660/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/TV_One.svg/2560px-TV_One.svg.png",
    group: "USA (DADDY LIVE)",
    tvgId: "TV.One.us",
  },
  {
    name: "TVLAND",
    url: "https://xyzdddd.mizhls.ru/lb/premium342/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/tv-land-us.png?raw=true",
    group: "USA (DADDY LIVE)",
    tvgId: "TV.Land.-.Eastern.us",
  },
  {
    name: "Unimas",
    url: "https://xyzdddd.mizhls.ru/lb/premium133/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/unimas-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "UniMas(East)(Spanish).us",
  },
  {
    name: "Universal Kids",
    url: "https://xyzdddd.mizhls.ru/lb/premium668/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/universal-kids-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Universal.Kids.us",
  },
  {
    name: "Univision",
    url: "https://xyzdddd.mizhls.ru/lb/premium132/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/univision-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "Univision.-.Eastern.Feed.us",
  },
  {
    name: "USA Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium343/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/usa-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "USA.Network.-.East.Feed.us",
  },
  {
    name: "VH1",
    url: "https://xyzdddd.mizhls.ru/lb/premium344/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/vh1-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "VH1.-.Eastern.Feed.us",
  },
  {
    name: "Viaplay Sports 1",
    url: "https://xyzdddd.mizhls.ru/lb/premium451/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/viaplay-sports-1-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Premier.Sports.1.HD.uk",
  },
  {
    name: "Viaplay Sports 2",
    url: "https://xyzdddd.mizhls.ru/lb/premium550/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/viaplay-sports-2-uk.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Premier.Sports.2.HD.uk",
  },
  {
    name: "VICE TV",
    url: "https://xyzdddd.mizhls.ru/lb/premium659/index.m3u8",
    logo: "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/vice-us.png?raw=true",
    group: "USA (DADDY LIVE)",
    tvgId: "VICE.us",
  },
  {
    name: "WETV",
    url: "https://xyzdddd.mizhls.ru/lb/premium655/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/we-tv-us.png",
    group: "USA (DADDY LIVE)",
    tvgId: "W(WomensTelevisionNetwork)(Pacific)(English).ca",
  },
  {
    name: "Willow Cricket",
    url: "https://xyzdddd.mizhls.ru/lb/premium346/index.m3u8",
    logo: "https://aimages.willow.tv/wlo_logo_200_200.jpg",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "Willow.Cricket.HDTV.(WILLOWHD).us",
  },
  {
    name: "Willow XTRA",
    url: "https://xyzdddd.mizhls.ru/lb/premium598/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/willow-xtra-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "WillowXtra.us",
  },
  {
    name: "WWE Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium376/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/635e715cb2f2c6d28e9691861d3d331dd040285b/countries/united-states/wwe-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "WWE.Network.us",
  },
  {
    name: "YES Network",
    url: "https://xyzdddd.mizhls.ru/lb/premium763/index.m3u8",
    logo: "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-states/yes-network-us.png",
    group: "SPORTS (DADDY LIVE)",
    tvgId: "YES.Network.us",
  },
];

export default ChannelList;
